### PR TITLE
Adding option of using existing proxy port

### PR DESCRIPTION
**Pull request by ncboodah**
We have a long-running process with existing config 
we'd like to reuse so that we won't have to start up 
a new proxy with each run we make.

### CODE REVIEW

**Comment by AutomatedTester** [comment]
I agree with @aerickson for the key. `existing_proxy_port_to_use` would make the code more readable

**Comment by ncboodah** [comment]
Thanks for your feedback! I have updated the commit to existing_proxy_port_to_use. Let me know if anything else needs to be changed.

**Comment by AutomatedTester** [comment]
landed in e5dc8cd

**Comment by AutomatedTester** [comment]
thanks for the patch!

**Pull request closed without merging**
